### ISSUE TITLE
[bug]: bind: no keybinding found for sequence "\ek"

### ISSUE THREAD

**Issue by sophiabrandt** [gokulsoumya/f#3]
Hello,
thank you for creating this plugin.

I'm using [kitty](https://sw.kovidgoyal.net/kitty/) as my terminal and [fish as interactive shell](https://wiki.archlinux.org/index.php/Fish#Setting_fish_as_interactive_shell_only).

Every time I restart kitty, I get the error: `bind: no binding found for sequence "\ek"`.
The key binding _does work_ though.

If I comment _out_ the following lines in `~/.config/fish/conf.d/f_key_bindings.fish`, I don't get the error:
```
if not bind \ek
    bind \ek __f_insert_from_picker
end

if not bind -M insert \ek
    bind -M insert \ek __f_insert_from_picker
end

function f_key_bindings_uninstall --on-event f_key_bindings_uninstall
    bind \ek | string match -e __f_insert_from_picker
    and bind -e \ek

    bind -M insert \ek | string match -e __f_insert_from_picker
    and bind -M insert -e \ek
end
```

Kitty version: kitty 0.17.4
fish: version 3.1.2
OS: Linux 5.4.44-1-MANJARO x86_64 GNU/Linux

Possibly related issue: [No binding found for sequence “\nbind -M visual ” #38](https://github.com/oh-my-fish/theme-budspencer/issues/38).

Thank you for any pointers on how to solve this!

**Comment by sudormrfbin** [comment]
`bind` prints the no keybinding found message because `Alt-K` isn't initially defined. That behavior is the expected one and it's supposed to be suppressed manually. In my fisher config, all errors during sourcing of the plugin files were being suppressed and I never noticed it. Thanks for pointing it out !
